spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka